[package]
name = "netcat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.13", features = ["derive"] }

# Colorization and ANSI escape sequence codes.
r3bl_tui = { version = "0.5.1" }
r3bl_ansi_color = { version = "0.6.9" }